# -*- coding: utf-8 -*-
"""RSScollector_Boeing_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ME-sLVDBQcAIH-svUbNNU8vO4GirR3Iq

Workflow:
1. Define Boeing Supplier Base
        ↓
2. Define Boeing Risk Categories
        ↓
3. Generate Supplier-Risk Searches
        ↓
4. Collect Articles from RSS Sources
        ↓
5. Clean and Standardize Article Content
        ↓
6. Identify Suppliers Mentioned
        ↓
7. Identify Risk Indicators Mentioned
        ↓
8. Map Indicators to Boeing Risk Categories
        ↓
9. Determine Primary Supplier & Risk Category
        ↓
10. Assess Source Quality
        ↓
11. Enrich with Commodity Context
        ↓
12. Export Structured Risk Signals
"""

!pip install feedparser pandas

import feedparser
import pandas as pd
import re

from bs4 import BeautifulSoup
from collections import Counter
from datetime import datetime

# take raw HTML removes HTML tags and return only the clean text
def clean_html(raw_text):

    if not raw_text:
        return ""

    soup = BeautifulSoup(raw_text, "html.parser")

    return soup.get_text(" ", strip=True)

# ============================================================
# Boeing RSS Collector V2
# Focus: Slow-moving supply chain deterioration signals
# ============================================================
# Supplier + Risk keyworkds lists

suppliers = {
    "Spirit AeroSystems": "Aerostructures",
    "GE Aerospace": "Propulsion Systems",
    "Pratt & Whitney": "Propulsion Systems",
    "Collins Aerospace": "Avionics & Aerospace Systems",
    "Honeywell Aerospace": "Avionics & Control Systems",
    "Safran": "Landing Gear & Aerospace Systems",
    "Rolls-Royce": "Propulsion Systems",
    "Hexcel": "Composite Materials",
    "Howmet Aerospace": "Engineered Metal Components",
    "Triumph Group": "Aerostructures & Systems",
    "Parker Hannifin": "Hydraulic Systems",
    "Moog": "Flight Control Systems",
    "Crane Aerospace": "Electronics & Sensors",
    "ATI": "Titanium Materials",
    "Arconic": "Aluminum Materials"
}


risk_categories = {

    # Tier 1: Primary slow-moving risks
    "production_quality": [
        "quality issue",
        "production quality issue",
        "supplier defect",
        "defect",
        "nonconformance",
        "quality escape",
        "audit finding",
        "inspection failure",
        "recall",
        "traveled work",
        "out-of-sequence work",
        "rework",
        "FAA finding",
        "quality control",
        "manufacturing quality control"
    ],

    "material_availability": [
        "material shortage",
        "raw materials",
        "titanium",
        "aluminum",
        "composites",
        "critical material",
        "availability of materials",
        "availability of essential materials",
        "sole-source supplier",
        "single source supplier"
    ],

    "logistics_delivery": [
        "delivery delay",
        "late delivery",
        "backlog",
        "lead time",
        "long-lead item",
        "supply chain constraint",
        "capacity constraint",
        "production bottleneck",
        "shipment delay",
        "supplier delay"
    ],

    # Tier 2: Early warning instability signals
    "labor_instability": [
        "strike",
        "work stoppage",
        "walkout",
        "labor dispute",
        "labor shortage",
        "union",
        "labor instability",
        "staffing shortage",
        "inexperienced workforce"
    ],

    "financial_distress": [
        "bankruptcy",
        "restructuring",
        "liquidity issue",
        "default",
        "credit downgrade",
        "financial distress",
        "insolvency",
        "going concern"
    ],

    # Tier 3: Strategic supply chain pressure
    "geopolitical_trade": [
        "tariff",
        "trade restriction",
        "export control",
        "import restriction",
        "sanction",
        "trade dispute",
        "sourcing restriction",
        "U.S.-China relations",
        "geopolitical risk"
    ],

    "economic_inflation": [
        "inflation",
        "inflationary pressure",
        "supplier price increase",
        "cost increase",
        "cost escalation",
        "cost overrun",
        "price escalation",
        "supplier cost estimate"
    ],

    # Tier 4: Sudden disruption signals
    "facility_incident": [
        "factory fire",
        "plant fire",
        "facility fire",
        "warehouse fire",
        "explosion",
        "facility shutdown",
        "plant shutdown",
        "flood",
        "earthquake",
        "storm damage",
        "natural disaster"
    ],

    "cybersecurity_risk": [
        "cyberattack",
        "cyber incident",
        "ransomware",
        "security breach",
        "data breach",
        "unauthorized access",
        "systems outage",
        "IT outage",
        "network disruption",
        "phishing"
    ]
}


# Flatten risk keywords for RSS searching
risk_terms = []

for category, keywords in risk_categories.items():
    risk_terms.extend(keywords)


# Optional: define category tiers for later filtering/analysis
risk_category_tiers = {
    "production_quality": "Tier 1",
    "material_availability": "Tier 1",
    "logistics_delivery": "Tier 1",

    "labor_instability": "Tier 2",
    "financial_distress": "Tier 2",

    "geopolitical_trade": "Tier 3",
    "economic_inflation": "Tier 3",

    "facility_incident": "Tier 4",
    "cybersecurity_risk": "Tier 4"
}

# Take text input and identifies which predefined risk categories are present
def get_risk_categories(text):
    matched_categories = []

    text = str(text).lower()

    for category, keywords in risk_categories.items():
        for keyword in keywords:
            if keyword.lower() in text:
                matched_categories.append(category)
                break

    return matched_categories

# Count the risks and determine the primary risk
def get_primary_risk_category(matched_terms):

    if not isinstance(matched_terms, list) or len(matched_terms) == 0:
        return "unknown"

    category_counts = {}

    for category, keywords in risk_categories.items():

        count = 0

        for term in matched_terms:
            if term.lower() in [k.lower() for k in keywords]:
                count += 1

        if count > 0:
            category_counts[category] = count

    if len(category_counts) == 0:
        return "unknown"

    return max(category_counts, key=category_counts.get)

# Figure out the primary supplier
def get_primary_supplier(text, matched_suppliers):

    if not matched_suppliers:
        return "Unknown"

    counts = {}

    text = str(text).lower()

    for supplier in matched_suppliers:
        counts[supplier] = text.count(supplier.lower())

    return max(counts, key=counts.get)


def enrich_signal(row):
    matched_suppliers = row.get("matched_suppliers", [])
    matched_terms = row.get("matched_risk_terms", [])

    full_text = f"{row.get('title', '')} {row.get('summary', '')}"

    primary_supplier = get_primary_supplier(
        full_text,
        matched_suppliers
    )

    primary_risk_category = get_primary_risk_category(matched_terms)

    return pd.Series({
        "primary_supplier": primary_supplier,
        "matched_supplier_count": len(matched_suppliers),
        "commodity": suppliers.get(primary_supplier, "Unknown"),
        "primary_risk_category": primary_risk_category,
        "risk_category_tier": risk_category_tiers.get(primary_risk_category, "Unknown")
    })

# RSS feeds

rss_feeds = {}

for supplier in suppliers.keys():

    supplier_query = supplier.replace(" ", "+")

    for risk in risk_terms:

        risk_query = risk.replace(" ", "+")

        name = f"{supplier}_{risk}"

        rss_feeds[name] = (
            f"https://news.google.com/rss/search?"
            f"q={supplier_query}+{risk_query}"
            "&hl=en-US&gl=US&ceid=US:en"
        )

print(len(rss_feeds))

# Collect RSS articles

articles = []

for query_name, feed_url in rss_feeds.items():
    feed = feedparser.parse(feed_url)

    for entry in feed.entries:
        title = entry.get("title", "")
        summary = clean_html(entry.get("summary", ""))
        link = entry.get("link", "")
        published = entry.get("published", "")

        text = f"{title} {summary}".lower()

        matched_suppliers = [
            supplier for supplier in suppliers
            if supplier.lower() in text
        ]

        matched_risks = [
            risk for risk in risk_terms
            if risk.lower() in text
        ]

        signal_types = get_risk_categories(text)

        articles.append({
            "query_name": query_name,
            "title": title,
            "published": published,
            "link": link,
            "matched_suppliers": matched_suppliers,
            "matched_risk_terms": matched_risks,
            "signal_types": signal_types,
            "summary": summary
        })

df = pd.DataFrame(articles)

# Remove duplicate articles
df = df.drop_duplicates(subset=["title", "link"])

# Ensures that the articles collected have at least one of each of the categories
df = df[
    (df["matched_suppliers"].apply(len) > 0) &
    (df["matched_risk_terms"].apply(len) > 0) &
    (df["signal_types"].apply(len) > 0)
]

enriched_cols = df.apply(enrich_signal, axis=1)
df = pd.concat([df, enriched_cols], axis=1)

print(f"Articles Found: {len(df)}")
df.head()

# Additional: Source Quality

def create_event_id(row):
    supplier = str(row.get("primary_supplier", "unknown")).lower().replace(" ", "_")
    category = str(row.get("primary_risk_category", "unknown")).lower()
    date = str(row.get("published", ""))[:16]

    return f"{supplier}_{category}_{date}"


source_quality_scores = {
    "Reuters": 5,
    "Bloomberg": 5,
    "Aviation Week": 5,
    "FAA": 5,
    "Boeing": 5,
    "Wall Street Journal": 5,
    "Financial Times": 5,
    "AP News": 4,
    "CNBC": 4,
    "FlightGlobal": 4,
    "Simple Flying": 3
}


def get_source_quality(text):
    text = str(text)

    for source, score in source_quality_scores.items():
        if source.lower() in text.lower():
            return score

    return 2


df["event_id"] = df.apply(create_event_id, axis=1)

df["source_quality_score"] = df["summary"].apply(get_source_quality)

df.head(10)

# Save as CVS file
output_filename = f"boeing_rss_signals_v2_{datetime.now().strftime('%Y%m%d_%H%M')}.csv"

df.to_csv(output_filename, index=False)

print(f"Saved to {output_filename}")