# -*- coding: utf-8 -*-
"""RSScollector_Boeing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WKRge9zr9fIkvVqPNhOpxzFquAs_85TE
"""

!pip install feedparser pandas

# Supplier + Risk keyworkds lists

suppliers = [
    "Boeing",
    "Spirit AeroSystems",
    "GE Aerospace",
    "RTX",
    "Collins Aerospace",
    "Pratt & Whitney",
    "Honeywell",
    "Safran",
    "Rolls-Royce",
    "Howmet Aerospace",
    "Hexcel",
    "Triumph Group"
]

risk_terms = [
    "strike", "labor dispute", "layoff", "shortage", "delay",
    "production halt", "quality issue", "defect", "inspection",
    "FAA", "sanction", "tariff", "export control",
    "fire", "flood", "earthquake", "cyberattack", "bankruptcy"
]

# RSS feeds

rss_feeds = {
    "Boeing Supply Chain": "https://news.google.com/rss/search?q=Boeing+supply+chain&hl=en-US&gl=US&ceid=US:en",
    "Boeing Supplier Disruption": "https://news.google.com/rss/search?q=Boeing+supplier+disruption&hl=en-US&gl=US&ceid=US:en",
    "Spirit AeroSystems Boeing": "https://news.google.com/rss/search?q=Spirit+AeroSystems+Boeing&hl=en-US&gl=US&ceid=US:en",
    "GE Aerospace Boeing": "https://news.google.com/rss/search?q=GE+Aerospace+Boeing&hl=en-US&gl=US&ceid=US:en",
    "FAA Boeing Inspection": "https://news.google.com/rss/search?q=FAA+Boeing+inspection&hl=en-US&gl=US&ceid=US:en"
}

# Check if its pulling articles
for source_name, feed_url in rss_feeds.items():

    feed = feedparser.parse(feed_url)

    print(source_name)
    print("Entries:", len(feed.entries))
    print("-"*50)

# Collect RSS articles

import feedparser
import pandas as pd

articles = []

for source_name, feed_url in rss_feeds.items():
    feed = feedparser.parse(feed_url)

    for entry in feed.entries:
        title = entry.get("title", "")
        summary = entry.get("summary", "")
        link = entry.get("link", "")
        published = entry.get("published", "")

        text = f"{title} {summary}".lower()

        matched_suppliers = [
            supplier for supplier in suppliers
            if supplier.lower() in text
        ]

        matched_risks = [
            risk for risk in risk_terms
            if risk.lower() in text
        ]

        articles.append({
            "source": source_name,
            "title": title,
            "published": published,
            "link": link,
            "matched_suppliers": matched_suppliers,
            "matched_risk_terms": matched_risks,
            "summary": summary
        })

df = pd.DataFrame(articles)

print(f"Articles Found: {len(df)}")
df.head()

# Save Daily File
from datetime import datetime

timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

filename = f"boeing_supply_signals_{timestamp}.csv"

df.to_csv(filename, index=False)

print(f"Saved: {filename}")

df