# -*- coding: utf-8 -*-
"""NewsAPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dzdLdMriR3NjKhi9gELzy69_3bENeg-V
"""

# Dependencies can be installed using: pip install requests python-dotenv openai

NEWS_API_KEY = "9af2368b8d1c40e5b45f47456a0c781e"

import requests
from datetime import datetime, timedelta

TOP_100_DISRUPTION_SIGNALS = [
 "supply shortage", "material shortage", "component shortage", "raw material shortage",
    "supplier disruption", "supplier shutdown", "factory shutdown", "plant closure",
    "production halt", "manufacturing delay", "capacity constraint", "capacity shortage",
    "equipment failure", "machinery breakdown", "quality issue", "product recall",
    "contamination", "defect", "safety violation", "regulatory violation",

    "labor strike", "worker strike", "union strike", "labor shortage",
    "workforce shortage", "layoffs", "civil unrest", "protest",
    "border closure", "customs delay", "trade restriction", "export restriction",
    "import restriction", "sanctions", "tariff", "trade war",
    "geopolitical tension", "political instability", "military conflict", "war",

    "port congestion", "port closure", "shipping delay", "freight delay",
    "container shortage", "vessel delay", "rail disruption", "truck driver shortage",
    "road closure", "airport disruption", "air cargo delay", "warehouse disruption",
    "logistics bottleneck", "transportation disruption", "route disruption", "supply chain disruption",

    "earthquake", "flooding", "hurricane", "typhoon",
    "wildfire", "drought", "winter storm", "extreme weather",
    "landslide", "volcanic eruption", "tsunami", "heatwave",
    "power outage", "energy shortage", "electricity shortage", "fuel shortage",
    "gas shortage", "oil price spike", "natural gas disruption", "grid failure",

    "cyberattack", "ransomware", "data breach", "IT outage",
    "system outage", "network outage", "software failure", "supplier cyberattack",
    "payment disruption", "bankruptcy", "insolvency", "credit downgrade",
    "financial distress", "price spike", "commodity price increase", "demand surge",

    "inventory shortage", "backlog", "order delay", "delivery delay",
    "lead time increase", "procurement delay", "contract dispute", "supplier dispute",
    "compliance investigation", "environmental regulation", "emissions restriction", "carbon regulation",
    "mining disruption", "refinery outage", "chemical spill", "hazardous materials incident",
    "cold chain failure", "temperature excursion", "food safety alert", "disease outbreak"
]

INDUSTRY_QUERY_PROFILES = {
    "semiconductors": """
        (semiconductor OR chip OR foundry OR wafer OR fab OR GPU OR lithography OR TSMC)
    """,

    "steel": """
        (steel OR iron ore OR coking coal OR blast furnace OR rebar)
    """,

    "automotive": """
        (automotive OR EV OR vehicle production OR battery)
    """
}


def build_disruption_query():
    return " OR ".join([f'"{x}"' for x in TOP_100_DISRUPTION_SIGNALS])


def build_industry_query(supply_base):
    normalized = supply_base.lower().strip()

    for industry, query in INDUSTRY_QUERY_PROFILES.items():
        if industry in normalized or normalized in industry:
            return " ".join(query.split())

    return f'"{supply_base}"'


def build_full_query(supply_base):
    industry_query = build_industry_query(supply_base)
    disruption_query = build_disruption_query()

    return f"""
        ({industry_query})
        AND
        ({disruption_query})
    """


def test_live_news_api(supply_base, max_results=5):

    query = " ".join(build_full_query(supply_base).split())

    print("QUERY:")
    print(query)

    from_date = (
        datetime.now() - timedelta(days=7)
    ).strftime("%Y-%m-%d")

    url = "https://newsapi.org/v2/everything"

    params = {
        "q": query,
        "language": "en",
        "sortBy": "publishedAt",
        "from": from_date,
        "pageSize": max_results,
        "apiKey": NEWS_API_KEY
    }

    response = requests.get(url, params=params)

    print("\nSTATUS:", response.status_code)

    data = response.json()

    if "articles" not in data:
        print(data)
        return

    articles = data["articles"]

    print(f"\nFOUND {len(articles)} ARTICLES\n")

    for i, article in enumerate(articles, start=1):

        print("=" * 60)
        print(f"ARTICLE #{i}")
        print("=" * 60)

        print("TITLE:")
        print(article.get("title"))

        print("\nSOURCE:")
        print(article.get("source", {}).get("name"))

        print("\nPUBLISHED:")
        print(article.get("publishedAt"))

        print("\nDESCRIPTION:")
        print(article.get("description"))

        print("\nURL:")
        print(article.get("url"))

        print("\n")

test_live_news_api("semiconductors")